---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

## 網站資料爬取
```{r}
#這是R Code Chunk
##第一次使用要先安裝
##install.packages("rvest")

library(rvest)

data=NULL
for(n in 1:5){
    ##目前NBA版最新頁數之index值為4606 (最新一頁不足20筆，所以我從再前一頁開始)
    i=4606-n
    pttNBA<-paste("https://www.ptt.cc/bbs/NBA/index",i,".html",sep="")
    pttContent<-read_html(pttNBA ,encoding="UTF-8")

    title <- pttContent %>% html_nodes(".title") %>% html_text()
    push <- pttContent %>% html_nodes(".nrec")  %>% html_text()
    aut <- pttContent %>% html_nodes(".author") %>% html_text()
    
    ##一頁共20筆資料，一共爬5頁分別裝在5個資料表，所以20*5=100筆
    if(n==1){
        data1=data.frame(Title=title,PushNum=push,Author=aut)
    }else if(n==2){
        data2=data.frame(Title=title,PushNum=push,Author=aut)
    }else if(n==3){
        data3=data.frame(Title=title,PushNum=push,Author=aut)
    }else if(n==4){
        data4=data.frame(Title=title,PushNum=push,Author=aut)
    }else {
        data5=data.frame(Title=title,PushNum=push,Author=aut)
    }
}

##5合1
data = rbind(data1, data2, data3, data4, data5)
##直接試印100則
print(data)
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
##印出100則
knitr::kable(data[1:100,c("Title","PushNum","Author")]) ##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
#這是R Code Chunk
nrow(data)

```
nrow() 用來算列數，得到100列，所以可以知道包含被刪掉的標題共爬出100篇文章

```{r}
#這是R Code Chunk
table(data$Author)

```
可以看到table中，有個作者叫Rambo
一共發了17則推文，是裡面發文數最多的人

心得:
我覺得NBA的文章都挺無聊的，可能因為我本身不太FOLLOW籃球，隨意點了幾則推文數爆的進去看，發現大家只是在閒聊或是分享看比賽心得，而且通常那些文章都是新聞或是LIVE的影片分享，對我來說，還是八卦版之類的版有趣一點
